services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: